### ISSUE TITLE
Font Awesome Icon Support in archetypes + markdown

### ISSUE THREAD

**Issue by adsail** [your-identity/hugo-theme-dimension#19]
Great work on this theme; it's beautiful! This may only be a matter of needing further instruction in the README, I've yet to have success referencing FA icons both in markdown and via the archetype `logo` field. FA appears to be part of theme. 

If this is just a matter of guidance, I would appreciate being pointed in the right direction, and more than happy to contribute to the README/docs thereafter as well.

**Comment by hexdae** [comment]
You are right, recently I modified the default logo to use images rather than font awesome icons in PR #16. The rationale behind it was that font awesome only provided a limited numbers of icons and it was quite complex to explain how to use them.

Try specifying the path to a custom image and let me know if it works. If you can update the README so that it makes this point clear, please go ahead and do so

**Comment by adsail** [comment]
@d-asnaghi Thanks for your response – I ultimately had [success](https://www.andrewsail.com) with custom images (but still wrestling with the CSS to eliminate the dotted line that indicates the image is a link). I'll follow-up with a PR to update the README.

**Comment by hexdae** [comment]
Happy to see you were able to get it to work. The website looks great. Thank you for your contribution

**Comment by hexdae** [comment]
After #20 I think we can close this issue, @adsail thanks for your help
