### ISSUE TITLE
Customization of the logo

### ISSUE THREAD

**Issue by catethos** [your-identity/hugo-theme-dimension#2]
How can I replace the "gem" logo by my own image? I have tried parameters like `logo`, `logoimage`, but none is working. Is it hard-coded?

**Comment by hexdae** [comment]
Hi @catethos The current implementation of the `logo` parameter only supports icons from `fa-icons` 4.7, here is a [list](https://fontawesome.com/v4.7.0/icons/) of possible values for the `logo` parameter.

just add this to your `_index.md`, where `<icon>` is any icon from that list
```yaml
---
<other parameters>
logo: <icon>
---
```

**Comment by hexdae** [comment]
Referencing Issue #3, You can select from [this list](https://fontawesome.com/icons?d=gallery&s=regular&m=free) all the Font Awesome Regular icons.

I'll close this issue if that's ok with you @catethos

**Comment by HeyItsWaters** [comment]
It would be neat to support the ability to use a custom Image as well as these icons.

**Comment by notcarbide** [comment]
I threw something together here to use an img as the icon instead of FontAwesome icons, if anyone wants to cherry-pick (or improve).

https://github.com/carbideband/hugo-theme-dimension/tree/img-icon2

**Comment by amita4ai** [comment]
I have two issues-- 1. Not able to see plots and images in blog posts and 2. Not able to change logo.

Regarding Issue1, I placed images in _static_ folder and tried InsertImage and kintr::include_graphic{"/image.png"} but nothing worked. Please tell me the exact way to show image in  _.Rmd_ posts.

Regarding Issue2, I wrote following command in "_index.md" file in content folder---

---
background: images/.jpg
description: An ML & AI Enthusiast
title: Dr. Amita Sharma
logo: <"fa fa-eye">
---


But logo doesn't appear. Help me out regarding these issues.

Thanks in advance.

Dr. Amita Sharma

**Comment by notcarbide** [comment]
@amita4ai 
If you're on the latest branch https://github.com/your-identity/hugo-theme-dimension/pull/12 adds a method for easily adding images to posts.
I'll create a PR to update the README to include this info soon but you can view the PR itself that is linked to see how to use it.

As for the logo, you need to look up the appropriate icon set for the icon you want to use on https://fontawesome.com. For example, to use the solid icon set for the eye icon, you would use `fas fa-eye` instead of `fa fa-eye` (which does not include the eye icon, that's why it's not showing up).

EDIT: I forgot that the `logo` param in the base version of this theme is only half of the fontawesome string for an icon. Try defining the icon set after the icon like this
`logo: "eye fas"`

Hope it helps!

**Comment by bhedder** [comment]
*

**Comment by hexdae** [comment]
I ended up implementing this feature natively in #16, please let me know if that branch works for you here and I'll merge it. Font awesome icons were kinda limiting and hard to use, so I decided to go with images instead. You can still use all of the icons available before by finding them on wikimedia (example [here](https://upload.wikimedia.org/wikipedia/commons/8/8e/Font_Awesome_5_regular_gem.svg)}

**Comment by hexdae** [comment]
I am going to close this issue since it was addressed in #16
